name: anilibria_app
description: Anilibria.tv client made using Flutter

publish_to: 'none'

version: 0.0.1

environment:
    sdk: '>=2.14.0 <3.0.0'

dependencies:
    adaptive_theme: ^2.3.0
    anilibria: ^0.0.1
    flutter:
        sdk: flutter
    flutter_hooks: ^0.18.1
    hooks_riverpod: ^1.0.2
    responsive_framework: ^0.1.5
    routemaster: ^0.10.0-dev5

dev_dependencies:
    flutter_lints: ^1.0.4
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
