name: anilibria_app
description: Anilibria.tv client made using Flutter

publish_to: 'none'

version: 0.0.1

environment:
    sdk: '>=2.14.0 <3.0.0'

dependencies:
    adaptive_theme: ^2.3.0
    anilibria: ^0.3.0
    expandable_text: ^2.2.0
    fancy_shimmer_image: ^2.0.1+1
    flutter:
        sdk: flutter
    flutter_hooks: ^0.18.1
    responsive_framework: ^0.1.5
    transparent_image: ^2.0.0
    sliver_tools: ^0.2.5
    video_player: ^2.2.7
    video_player_web_hls: ^0.1.11+2
    go_router: ^2.5.7
    flutter_riverpod: ^1.0.3
    better_player: ^0.0.81

dev_dependencies:
    flutter_lints: ^1.0.4
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
