name: anilibria_app
description: Anilibria cross-platform client

publish_to: 'none'

version: 0.0.1

environment:
    sdk: '>=2.14.0 <3.0.0'

dependencies:
    adaptive_theme: ^3.0.0
    anilibria: ^0.8.4
    expandable_text: ^2.2.0
    fancy_shimmer_image: ^2.0.1+1
    flutter:
        sdk: flutter
    responsive_framework: ^0.2.0
    transparent_image: ^2.0.0
    sliver_tools: ^0.2.5
    video_player: ^2.2.7
    video_player_web_hls: ^0.1.11+2
    go_router: ^5.0.0
    flutter_riverpod: ^1.0.3
    audio_video_progress_bar: ^0.10.0
    wakelock: ^0.6.0+1
    font_awesome_flutter: ^10.0.0
    url_launcher: ^6.0.18
    html_unescape: ^2.0.0
    # TODO: upstream package when it will use an m3 navigation bar
    adaptive_navigation:
        git: 
            url: https://github.com/arslee07/material-components-flutter-adaptive
            ref: m3-navigation-bar
            path: adaptive_navigation


dev_dependencies:
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
